# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rankings',
            new_name='Ranking',
        ),
    ]
