# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0003_auto_20160603_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='ranking',
            new_name='score',
        ),
    ]
