# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0004_auto_20160603_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.CharField(default='', max_length=200),
        ),
    ]
