# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0005_auto_20160603_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
