# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0008_auto_20160609_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='username',
            new_name='user',
        ),
    ]
