# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0009_auto_20160609_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
