# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-11 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankings', '0010_ranking_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
