# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-07 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CountryInfo', '0005_sport_sport_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_medal_winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_medal_winner+', to='CountryInfo.Country')),
                ('gold_medal_winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_medal_winner+', to='CountryInfo.Country')),
                ('silver_medal_winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_medal_winner+', to='CountryInfo.Country')),
                ('sport_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CountryInfo.Sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
