# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSelections', '0003_auto_20160609_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='bronze_medal_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze_medal_winner+', to='CountryInfo.Country'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='silver_medal_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver_medal_winner+', to='CountryInfo.Country'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='sport_name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
