# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSelections', '0006_userselection_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselection',
            old_name='winner',
            new_name='gold_winner',
        ),
    ]
