# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSelections', '0007_auto_20160614_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='bronze_medal_winner',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='gold_medal_winner',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='silver_medal_winner',
        ),
        migrations.AddField(
            model_name='userselection',
            name='bronze_winner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userselection',
            name='silver_winner',
            field=models.CharField(default='', max_length=200),
        ),
    ]
