# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserSelections', '0009_auto_20160614_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EventingSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(default='Eventing', max_length=200)),
                ('place', models.CharField(default='none', max_length=200)),
                ('bronze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze+', to='UserSelections.EventingOptions')),
                ('gold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold+', to='UserSelections.EventingOptions')),
                ('silver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver+', to='UserSelections.EventingOptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
