# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSelections', '0010_auto_20160615_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventingselection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
