# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-19 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserSelections', '0015_auto_20160617_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventingselection',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='womens_all_around_gymnasticsselection',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventingselection',
            name='bronze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze+', to='UserSelections.eventingOptions'),
        ),
        migrations.AlterField(
            model_name='eventingselection',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold+', to='UserSelections.eventingOptions'),
        ),
        migrations.AlterField(
            model_name='eventingselection',
            name='silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver+', to='UserSelections.eventingOptions'),
        ),
    ]
