# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_full_name', models.CharField(default='', max_length=200)),
                ('country_abbr_name', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='sports_participating',
            field=models.ManyToManyField(blank=True, to='CountryInfo.Sport'),
        ),
    ]
