# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-02 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0002_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='sports_participating',
            field=models.ManyToManyField(blank=True, to='CountryInfo.Sport'),
        ),
    ]
