# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0003_athlete_sports_participating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='winner_type',
            field=models.CharField(choices=[('IN', 'Individual'), ('TM', 'Team')], default='TM', max_length=2),
        ),
    ]
