# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0004_sport_winner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_slug',
            field=models.SlugField(default=''),
        ),
    ]
