# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0005_sport_sport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_description',
            field=models.TextField(default='Sport Description'),
        ),
    ]
