# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0006_sport_sport_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sports_participating',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sports_participating',
        ),
        migrations.AddField(
            model_name='sport',
            name='athlete',
            field=models.ManyToManyField(blank=True, to='CountryInfo.Athlete'),
        ),
    ]
