# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-15 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0008_sport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='athlete',
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.ManyToManyField(blank=True, to='CountryInfo.Sport'),
        ),
    ]
