# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-17 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0009_auto_20160614_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='competition_dates',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='favorite',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='scoring',
            field=models.TextField(default=''),
        ),
    ]
