# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-18 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0010_auto_20160616_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='competition_dates',
            field=models.TextField(default='dates'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='favorite',
            field=models.TextField(default='favorites'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='scoring',
            field=models.TextField(default='score'),
        ),
    ]
