# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0011_auto_20160617_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
