# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-28 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0012_sport_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='source_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='source_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
