# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-02 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0013_auto_20160627_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='source_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
