# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0014_auto_20160701_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='rankings_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='view_rankings',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
