# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0015_auto_20160707_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='locked_day',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='sport',
            name='locked_time',
            field=models.IntegerField(default=24),
        ),
    ]
