# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-03 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountryInfo', '0017_auto_20160709_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='bronze',
            field=models.CharField(blank=True, default='TBD', max_length=200),
        ),
        migrations.AddField(
            model_name='sport',
            name='gold',
            field=models.CharField(blank=True, default='TBD', max_length=200),
        ),
        migrations.AddField(
            model_name='sport',
            name='silver',
            field=models.CharField(blank=True, default='TBD', max_length=200),
        ),
    ]
